### ISSUE TITLE
How can I create my own rpi23_3g1g_kernel.zip?

### ISSUE THREAD

**Issue by WheezyE** [Itai-Nelken/RPi-3g-1g-kernel-wine#1]
I would like to make some Pi3 3G/1G kernels for one of my scripts.  Botspot gave me permission to use their kernel-switching method in my script.  I'm planning to compile a 3G/1G kernel on-device ([with Botspot's method in my script](https://github.com/WheezyE/Winelink/blob/57d1e11d1d2594d7a860bb30cf1b4cb2e8bb3a76/install_winelink.sh#L691)), then zip up the linux folder on-device.

Since it takes a long time, I just wanted to ask if there was anything else I needed to do, or if you had any insights on compiling/packing these kernels.

**Comment by Itai-Nelken** [comment]
The last time I compiled the kernel was over a year ago, so I don't really remember what I did.

I think I followed the [rpi docs](https://www.raspberrypi.com/documentation/computers/linux_kernel.html) but I commented out `CONFIG_VMSPLIT_2G=y` and set `CONFIG_VMSPLIT_3G=y` in the `.config` file. The exact steps are in the pi-apps script.

As for packaging the compiled kernel as a zip, I think I simply zipped the whole `linux` folder.

**Comment by WheezyE** [comment]
Thank you very much. I’ve got my kernel compiling as I type. Did you run into any problems with upload file limits or bandwidth on GitHub?

**Comment by Itai-Nelken** [comment]
As long as you use the releases there shouldn't be any problem although I did notice that the zip became bigger in each of the releases I uploaded in this repo, so maybe the size limit will be a problem in the future?

**Comment by WheezyE** [comment]
Thank you for your insight. Have good one! 😃
